name: powersync_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.12.0
  flutter: ^3.44.0

dependencies:
  env:
    path: ../env
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.6
  powersync: ^2.3.1
  shared:
    path: ../shared
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0
